#!/bin/bash

# This script is meant to be run after Pycharm's "test_lc_gps",
# which is a run configuration. Since GPS may require root permissions,
# the "htmlcov" folder generated by "test_lc_gps" may have root file
# permissions, too. This script copies and reowns "htmlcov" so
# a normal user can check report results without using a web
# browser with root permissions which, by the way, is difficult.
# You can run several scripts via the "multirun" Pycharm plugin.

me=`basename "$0"`
currentdir=`pwd`
dfolder=`echo /home/kaz/Downloads/htmlcov_gps`

echo "Running $me..."
echo "My current working directory is: $currentdir"
echo "Copying htmlcov folder to $dfolder..."
cp -rf tests/htmlcov/. $dfolder
chown -R kaz:kaz $dfolder