name: Workflow CODECOV + CODECLIMATE for library lowell-mat
on: [push, workflow_dispatch]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.7'
    steps:
    - uses: actions/checkout@master

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7

    - name: LOWELL -> INSTALL PYTHON VIRTUAL ENVIRONMENT
      run: |
        pip install wheel 
        pip install pytest
        pip install pytest-cov
        pip install git+https://github.com/LowellInstruments/bluepy.git

    - name: LOWELL -> RUNNING TESTS and COVERAGE ANALYSIS
      run: |
        # XML output is a file, HTML are folders
        pytest --cov=./ tests/ --cov-report xml:cov.xml --cov-report term
        # other options
        # pytest --cov=./ tests/ --cov-report html:cov_html
        
    - name: LOWELL -> UPLOAD COVERAGE report to CODE CLIMATE
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      with:
        coverageCommand: pytest --cov=./ tests/ --cov-report xml:cov.xml --cov-report term
        coverageLocations: ${{github.workspace}}/cov.xml:coverage.py
        debug: true

    - name: LOWELL -> UPLOAD COVERAGE report to COVECOD
      uses: codecov/codecov-action@v2
      with:
      
        # only private repositories need TOKEN
        # token: ${{ secrets.CODECOV_TOKEN }}
        
        files: ./cov.xml
        directory: ./coverage/reports/
        env_vars: OS,PYTHON
        path_to_write_report: ./coverage/codecov_report.txt
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true
