name: Workflow CODECOV + CODECLIMATE for library lowell-mat
on: [push, workflow_dispatch]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.7'
    steps:
    - uses: actions/checkout@master

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7

    - name: LOWELL -> INSTALL PYTHON VIRTUAL ENVIRONMENT
      run: |
        pip install wheel 
        pip install pytest
        pip install pytest-cov
        pip install git+https://github.com/LowellInstruments/bluepy.git
        wget https://raw.githubusercontent.com/LowellInstruments/lowell-mat/master/requirements.txt
        pip install -r requirements.txt

    - name: LOWELL -> RUNNING TESTS and COVERAGE ANALYSIS
      run: |
        # pytest VS python -m pytest -> latter adds current directory to sys.path
        # XML output is a file, HTML are folders
        python -m pytest --cov=./ tests/ --cov-report xml:cov.xml --cov-report term
        # other options
        # python -m pytest --cov=./ tests/ --cov-report html:cov_html
        
    - name: LOWELL -> UPLOAD COVERAGE report to CODE CLIMATE
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      with:
        coverageCommand: python -m pytest --cov=./ tests/ --cov-report xml:cov.xml --cov-report term
        coverageLocations: ${{github.workspace}}/cov.xml:coverage.py
        debug: true
